### ISSUE TITLE
Wallpaper 

### ISSUE THREAD

**Issue by iMonkr** [modkavartini/klwp#1]
How to add our custom wallpaper?

**Comment by modkavartini** [comment]
you can change the link in `fetchImg` to a self-hosted git repo, which would be easier if you fork this one, then change the items in the `walls` folder and setting the correct number in the `wallNum.txt` file. you might also want to keep in mind of the specific resolution/ratio size of the wallpapers to upload. p.s. i think i already answered your question in discord (?) if not, sorry for the late reply :3
